// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniScore.API.Data;

#nullable disable

namespace UniScore.API.Migrations
{
    [DbContext(typeof(UniscoreContext))]
    [Migration("20250610135616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniScore.API.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("UniScore.API.Models.CriterioAvaliacao", b =>
                {
                    b.Property<int>("IdCriterio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCriterio"));

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<string>("NomeCriterio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCriterio");

                    b.HasIndex("IdEvento");

                    b.ToTable("CriterioAvaliacao");
                });

            modelBuilder.Entity("UniScore.API.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoEvento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Local")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("NotaMaxima")
                        .HasColumnType("real");

                    b.Property<float>("NotaMinima")
                        .HasColumnType("real");

                    b.HasKey("IdEvento");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("UniScore.API.Models.EventoProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Evento_Projeto");
                });

            modelBuilder.Entity("UniScore.API.Models.InformacoesComplementares", b =>
                {
                    b.Property<int>("IdInformacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInformacao"));

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoComplementar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdInformacao");

                    b.HasIndex("IdProjeto");

                    b.ToTable("InformacoesComplementares");
                });

            modelBuilder.Entity("UniScore.API.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("int");

                    b.Property<int>("IdCriterio")
                        .HasColumnType("int");

                    b.Property<float>("NotaProjeto")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdAvaliacao");

                    b.HasIndex("IdCriterio");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("UniScore.API.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPessoa");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("UniScore.API.Models.PessoaTipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<byte>("IdTipoUsuario")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Pessoa_TipoUsuario");
                });

            modelBuilder.Entity("UniScore.API.Models.Projeto", b =>
                {
                    b.Property<int>("IdProjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjeto"));

                    b.Property<string>("DescricaoProjeto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Integrantes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("NotaFinal")
                        .HasColumnType("real");

                    b.Property<string>("Turma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProjeto");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("UniScore.API.Models.TipoUsuario", b =>
                {
                    b.Property<byte>("IdTipoUsuario")
                        .HasColumnType("tinyint");

                    b.Property<string>("PapelUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuario");

                    b.HasData(
                        new
                        {
                            IdTipoUsuario = (byte)1,
                            PapelUsuario = "Coordenador"
                        },
                        new
                        {
                            IdTipoUsuario = (byte)2,
                            PapelUsuario = "Avaliador"
                        },
                        new
                        {
                            IdTipoUsuario = (byte)3,
                            PapelUsuario = "ProfessorAdmin"
                        });
                });

            modelBuilder.Entity("UniScore.API.Models.Avaliacao", b =>
                {
                    b.HasOne("UniScore.API.Models.Pessoa", "Pessoa")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScore.API.Models.Projeto", "Projeto")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("UniScore.API.Models.CriterioAvaliacao", b =>
                {
                    b.HasOne("UniScore.API.Models.Evento", "Evento")
                        .WithMany("CriteriosAvaliacao")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("UniScore.API.Models.EventoProjeto", b =>
                {
                    b.HasOne("UniScore.API.Models.Evento", "Evento")
                        .WithMany("EventosProjetos")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScore.API.Models.Projeto", "Projeto")
                        .WithMany("EventosProjetos")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("UniScore.API.Models.InformacoesComplementares", b =>
                {
                    b.HasOne("UniScore.API.Models.Projeto", "Projeto")
                        .WithMany("InformacoesComplementares")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("UniScore.API.Models.Nota", b =>
                {
                    b.HasOne("UniScore.API.Models.Avaliacao", "Avaliacao")
                        .WithMany("Notas")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScore.API.Models.CriterioAvaliacao", "CriterioAvaliacao")
                        .WithMany("Notas")
                        .HasForeignKey("IdCriterio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("CriterioAvaliacao");
                });

            modelBuilder.Entity("UniScore.API.Models.PessoaTipoUsuario", b =>
                {
                    b.HasOne("UniScore.API.Models.Pessoa", "Pessoa")
                        .WithMany("PessoasTiposUsuario")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScore.API.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("PessoasTiposUsuario")
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("UniScore.API.Models.Avaliacao", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("UniScore.API.Models.CriterioAvaliacao", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("UniScore.API.Models.Evento", b =>
                {
                    b.Navigation("CriteriosAvaliacao");

                    b.Navigation("EventosProjetos");
                });

            modelBuilder.Entity("UniScore.API.Models.Pessoa", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("PessoasTiposUsuario");
                });

            modelBuilder.Entity("UniScore.API.Models.Projeto", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("EventosProjetos");

                    b.Navigation("InformacoesComplementares");
                });

            modelBuilder.Entity("UniScore.API.Models.TipoUsuario", b =>
                {
                    b.Navigation("PessoasTiposUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
